### ISSUE TITLE
Need username and password to sign in

### ISSUE THREAD

**Issue by Rac3rZer0** [MrCrayfish/MrCrayfishDeviceMod#98]
#  **Need username and password to sign in**
Like most real _PCs_ Passwords and Pins are needed so people don't access your private info. If this feature is **not** added people will see things they **shouldn't** see.

## **Todo List:**

1. [ Create Password to sign in ]
2. [ Create Username in settings ]
3. [ Create Multiple users with admins permissions, regular users, and guests ]
4. [ Create pin, password, and 2FA ( 2 Factor Authentication ( If possible ) ) ]
5. [ Create Lockscreen Background Picture / Color ]

**Comment by ShazerHD** [comment]
This has been said before. No username/passwords for privacy reasons!

**Comment by MrCrayfish** [comment]
Closed. I am avoid this due to people who WILL enter their real passwords as the password for the laptop. Any person with OP permission can then read their password in plain text. "But crayfish, just encrypt it", No because you need a master key and who decides on that key? "You're being lazy crayfish", No I'm not, I'm looking out for your privacy.
